name: sqlmigrate
description: A lightweight CLI for managing database migrations in Dart/Flutter projects.
version: 0.1.0
repository: https://github.com/pretodev/sqlmigrate

environment:
  sdk: '>=3.7.0 <4.0.0'

executables:
  sqlmigrate:

# Add regular dependencies here.
dependencies:
  uuid: ^4.5.1
  meta: ^1.16.0
  args: ^2.6.0
  path: ^1.9.1
  auto_injector: ^2.0.5
  yaml: ^3.1.3
  cli_util: ^0.4.2
  postgres: ^3.5.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
